### ISSUE TITLE
Why is this not written in pure Javascript?

### ISSUE THREAD

**Issue by abrkn** [femto113/node-skip32#1]

**Comment by imuli** [comment]
@abrkn If you are looking for a pure javascript version - I did a straightforward reading over of the C, which yielded [this](https://github.com/imuli/javascript/blob/master/skip32.js). Averages slightly faster than the native version here.

**Comment by femto113** [comment]
Pure javascript would be great.  The performance comparisons I did 3 years ago were close to an order of magnitude in favor of the C/C++  I've got some code that uses this extremely heavily, if tests run clear and performance is at least as good as the C version I'll go ahead and merge in the code from @imuli. Even if it is not as fast it would make sense to release it as its own module (e.g. skip32-pure).

**Comment by femto113** [comment]
Informal tests show that the port by @imuli is about 1.5x faster than the C version (running node v0.12.0 on MacBook Pro with an Intel Core I5 running OS X 10.10.3) so I've gone ahead and merged it in.  @abrkn let me know if you hit any issues with it.  @imuli if you send me your name and email address I'll add you to the contributors list in package.json.

**Comment by femto113** [comment]
Fixed by pull request #2.

**Comment by imuli** [comment]
Imuli and i@imu.li work just fine (and that's what I'd use if ever I put anything on npm), thank you!

**Comment by femto113** [comment]
Reopening this based on further testing.  Interestingly, in a complex app that makes heavy use of Skip32 I'm seeing roughly 5x _worse_ performance for the javascript version vs the C/C++ version.  Profiling shows almost all of the time is spent in Skip32.round16().  I don't have any good theory off the top of my head why it would be faster for the trivial tests and not here, but will investigate when I have time.

**Comment by femto113** [comment]
So more disconcertingly I discovered I get different results for some inputs between the C and javascript versions.  I've unpublished the javascript version for now until I can diagnose why (I suspect it has to do with the way overflows are handled in byte math vs integer math).

**Comment by abrkn** [comment]
Can you post some test vectors?

**Comment by imuli** [comment]
So I've run the first millionish inputs for the test key with the C without the node wrapper and both javascript versions with this:

```
var Skip32 = require('./skip32.js').Skip32; // or build/Realease/skip32
var KEY = [ 0x00,0x99,0x88,0x77,0x66,0x55,0x44,0x33,0x22,0x11 ];
var s = new Skip32(KEY);
var N = 2 << 20;
for (var i = 0; i < N; i++) {
  var e;
  e = s.encrypt(i);
  console.log(i.toString(16), e.toString(16));
}
```

and

```
unsigned
ldu32(unsigned char *buf){
  return (buf[0]<<24) + (buf[1]<<16) + (buf[2]<<8) + (buf[3]<<0);
}

void
stu32(unsigned char *buf, unsigned n){
  buf[0] = (n>>24) & 0xff;
  buf[1] = (n>>16) & 0xff;
  buf[2] = (n>>8) & 0xff;
  buf[3] = (n>>0) & 0xff;
}

int
main(int argc, char **argv){
  unsigned i, N = 2<<20;
  BYTE key[10] = { 0x00,0x99,0x88,0x77,0x66,0x55,0x44,0x33,0x22,0x11 };
  BYTE buf[4];
  for(i=0;i<N;i++){
    stu32(buf, i);
    skip32(key, buf, 1);
    printf("%x %x\n", i, ldu32(buf));
  }
  return 0;
}
```

I get identical outputs for all three. Presumably you had problems with a different key?

Time wise, I get C < pure javascript < native javascript on an i5-3337U @ 1.8GHz.

**Comment by imuli** [comment]
More thoroughly: I also get identical outputs for the first two millionish values when I simply feed the output value back into the function, `v = s.encrypt(v)` in a loop. Even when I also xor the output value with the key, `for(j=0;j<10;j++){key[j]^=buf[j%4]}`. So, I'm kinda at a loss for mismatched test values!

Also for the feedback one, I see a much reduced performance gap, but the pure js version still slightly faster.

**Comment by femto113** [comment]
I think I found the issue.  Built into the C++ constructor was (mostly undocumented) logic to repeat the given key if it is less than 10 bytes long:

```
Skip32(BYTE *key, int keylen) { for (int i = 0; i < 10; i++) _key[i] = key[i % keylen]; }
```

I think original motivation was to reduce the chance that users would accidentally use keys with lots of 0's in them.  I don't know if this is really a great design, but for backwards compatibility I think we should include comparable logic in the javascript version for now.  (I'll take a look at the perl version that inspired this to see if they did something similar, if they didn't then we can dump this logic in a 2.0 verision.)  I've implemented this along the lines of 

```
function Skip32(key) {
    this.key = new Uint8Array(10);
    for (var i = 0; i < 10; i++) this.key[i] = key[i % key.length];
 };
```

This might also explain the observed performance difference, since repeated casting of undefined to 0 is probably not free.

**Comment by abrkn** [comment]
Good find.

**Comment by femto113** [comment]
I checked and the perl version enforces 10 byte keys in the [constructor](https://github.com/alestic/Crypt-Skip32/blob/master/lib/Crypt/Skip32.pm#L31)

```
my @key_bytes = unpack('C*', $key);
croak "key must be 10 bytes long"
  unless scalar @key_bytes == 10;
```

**Comment by femto113** [comment]
I have verified that this fixes the performance issues seen in my app, and the pure javascript version now performs faster than the C++ version.  This has been published to NPM as version 1.2.1, so I'm closing this and will create another issue to track getting rid of the key extension logic.

**Comment by abrkn** [comment]
I have an idea on how to make this work. Currently we do:

`var skip32 = require('skip32').Skip32;`

How about new code does:

`var skip32 = require('skip32');`

...which can follow the standard (enforce key length of exactly 10)

And we can define `skip32.Skip32` as the "legacy" (which does use more of key than 10)

**Comment by imuli** [comment]
That seems sensible.

**Comment by femto113** [comment]
That's clever, but sadly I think that's ultimately an argument against it.  Crypto libraries in particular have a responsibility to behave in maximally obvious ways (yes, I know I'm a hypocrite).  I'm thinking to release a 2.X version that pukes on short keys, but could include an explicit config option to restore the old behavior.   Something like:

```
var skip32 = require('skip32');
skip32.extendShortKeys = true;
```

and/or

```
var Skip32 = require('skip32').Skip32;
var s = new Skip32(key, { extendShortKeys: true });
```

**Comment by abrkn** [comment]
+1

On Mon, Mar 30, 2015 at 9:14 AM, Ken Woodruff notifications@github.com
wrote:

> That's clever, but sadly I think that's ultimately an argument against it.
> Crypto libraries in particular have a responsibility to behave in maximally
> obvious ways (yes, I know I'm a hypocrite). I'm thinking to release a 2.X
> version that pukes on short keys, but could include an explicit config
> option to restore the old behavior. Something like:
> 
> var skip32 = require('skip32');
> skip32.extendShortKeys = true;
> 
> and/or
> 
> var Skip32 = require('skip32').Skip32;
> var s = new Skip32(key, { extendShortKeys: true });
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/femto113/node-skip32/issues/1#issuecomment-87576512.

## 

Andreas Brekken
