### ISSUE TITLE
Sync with php implementation

### ISSUE THREAD

**Issue by manico** [femto113/node-skip32#6]
This implementations accepts string as key:
https://github.com/piersroberts/Skip32

Is it possible to to the same here or do we have to convert string to byte array?

**Comment by femto113** [comment]
The code doesn't currently take a hex-encoded key ala the PHP, but I'd accept a pull request that added that feature.

**Comment by femto113** [comment]
NPM is being crabby at the moment but as soon as I can get it working this will be published as version 1.3.0

**Comment by manico** [comment]
How about also removing `console.log` in lpad?
It will pollute logs when this lib is used.

**Comment by femto113** [comment]
ah ya good catch

**Comment by femto113** [comment]
ok published
